soundscapes/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from rest_framework.routers import DefaultRouter

from episodes import views

# API router
router = DefaultRouter()
router.register(r'episodes', views.EpisodeViewSet)

show_patterns = [
    url(r'^$', views.ShowListView.as_view(), name='list'),
    url(r'^new/$', views.ShowCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.ShowDetailView.as_view(), name='detail'),
    # expose show.refresh
    url(r'^(?P<slug>[\w-]+)/refresh$', views.refresh, name='refresh'),
]

episode_patterns = [
    url(r'^(?P<pk>\d+)/$', views.EpisodeDetailView.as_view(), name='detail'),
]

segment_patterns = [
    url(r'new/$', views.SegmentCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.SegmentDetailView.as_view(),name='detail'),
]

urlpatterns = patterns('',
    url(r'^$', views.FeedView.as_view(), name = 'feed_view'),
    url(r'^api/', include(router.urls)),

    url(r'^shows/', include(show_patterns, namespace = 'show')),
    url(r'^episodes/', include(episode_patterns, namespace = 'episode')),
    url(r'^segments/', include(segment_patterns, namespace = 'segment')),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

episodes/models.py
from unipath import Path

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

from .handlers.downloads import download_file
from .handlers.rss import RSSHandler, RSSShowHandler, RSSEpisodeHandler
from .handlers.image import extract_color_scheme, serialize_color_scheme
from .handlers.waveform import WaveformHandler

# Decimal field kwargs for moments and segments
TIME_RESOLUTION = {'max_digits': 10, 'decimal_places': 2}

class ShowManager(models.Manager):
    def create_from_rss_url(self, rss_url, **kwargs):
        rss_show = RSSShowHandler(rss_url)
        kwargs.update(rss_show.show_kwargs())
        return self.create(**kwargs)

class Show(models.Model):
    """ A collection of Episodes, plugged in to an RSS podcast feed """
    name = models.CharField(unique = True, max_length = 30)
    slug = models.SlugField(unique = True)
    rss_url = models.URLField(unique = True)

    image_url = models.URLField()
    image = models.ImageField(blank = True)

    color_scheme = models.TextField()

    objects = ShowManager()

    def get_absolute_url(self):
        return reverse('show:detail', kwargs = {'slug': self.slug})

    def get_image_url(self):
        if self.image:
            return self.image.url
        else:
            return None

    def download_image(self):
        """ Download the image

        Images are downloaded if the image FileFiled is empty or if the
        file doesn't exist on the server.
        """
        if not self.image or not Path(self.image.path).exists():
            self.image = download_file(self.image_url)
            self.save()

    def extract_color_scheme(self):
        if not self.image:
            raise AssertionError('Logo is not available')

        color_scheme = extract_color_scheme(self.image.path)
        self.color_scheme = serialize_color_scheme(color_scheme)
        self.save()

    def refresh(self, max = 10):
        """ Create episodes from new RSS entries

        Evaluates uniqueness based on "rss_entry" field.

        max: int, number of entries to retrieve. A max number of entries
             are fetched before determining uniquess. Passing None will
             fetch all episodes.

        TODO: add "revert" as an optional argument.
        TODO: hash the rss_entry instead of comparing full json
        """
        all_entries = RSSHandler(self.rss_url)['entries'][0:max]

        current_entries = self.episode_set.values_list('rss_entry', flat = True)

        def compare_rss_entry_dump(rss_entry):
            return RSSEpisodeHandler(rss_entry).rss_entry_dump not in current_entries
        new_entries = filter(compare_rss_entry_dump, all_entries)

        for rss_entry in new_entries:
            self.episode_set.create_from_rss_entry(rss_entry)

    def __str__(self):
        return self.name

class EpisodeManager(models.Manager):
    def create_from_rss_entry(self, rss_entry, **kwargs):
        entry_handler = RSSEpisodeHandler(rss_entry)
        kwargs.update(entry_handler.episode_kwargs())
        return self.create(**kwargs)

class Episode(models.Model):
    """ A RSS entry from a podcast feed """
    show = models.ForeignKey(Show)
    slug = models.SlugField(unique = True)
    rss_entry = models.TextField()

    released = models.DateTimeField()
    title = models.CharField(max_length = 80)

    duration = models.FloatField(null = True)

    mp3_url = models.URLField(unique = True)
    mp3 = models.FileField(max_length = 200, blank = True)

    objects = EpisodeManager()

    def get_absolute_url(self):
        return reverse('episode:detail', kwargs = {'pk': self.pk})

    def get_mp3_url(self):
        # can be replaced with source='mp3.url' in the serializer
        if self.mp3:
            return self.mp3.url
        else:
            return None

    def __str__(self):
        return '{show}: {title}'.format(show = self.show, title = self.title)

    def download(self):
        """ Download the episode

        Episodes are downloaded if the mp3 FileField is empty or if the file
        doesn't exist on the server.

        TODO: use case for "overwrite" as an optional argument?
        """
        if not self.mp3 or not Path(self.mp3.path).exists():
            self.mp3 = download_file(self.mp3_url)
            self.save()

    def analyze(self, reset):
        if not self.mp3:
            raise AssertionError('No episode file. Download episode first.')

        try:
            has_waveform = (self.waveform is not None)
        except Waveform.DoesNotExist:
            has_waveform = False

        if has_waveform and reset:
            self.waveform.delete()
            has_waveform = False

        if not has_waveform:
            waveform_handler = WaveformHandler(self.mp3.path, reset = reset)
            Waveform.objects.create(episode = self, **waveform_handler.waveform_kwargs())

class Segment(models.Model):
    """ A section of an Episode

    TODO: validate time fields in clean method
    """
    episode = models.ForeignKey(Episode, related_name = 'segments')

    start_time = models.DecimalField(**TIME_RESOLUTION)
    end_time = models.DecimalField(**TIME_RESOLUTION)

class Waveform(models.Model):
    episode = models.OneToOneField(Episode, primary_key = True)
    interval = models.IntegerField()
    values = models.TextField()
    min = models.FloatField()
    max = models.FloatField()

    def delete(self, *args, **kwargs):
        analysis_txt = Path(self.episode.mp3.path).name + '.csv'
        analysis_txt = Path(settings.ANALYSES_DIR, analysis_txt)
        if analysis_txt.exists():
            analysis_txt.remove()
        return super(Waveform, self).delete(*args, **kwargs)

class Tag(models.Model):
    name = models.CharField(max_length = 150)
    segment = models.ForeignKey(Segment, related_name = 'tags',
                                related_query_name = 'tag')

episodes/forms.py
from django import forms
from django.core.urlresolvers import reverse

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Show, Segment

class ShowForm(forms.ModelForm):
    rss_url = forms.URLField()

    class Meta:
        model = Show
        fields = ('rss_url', )

    def __init__(self, *args, **kwargs):
        super(ShowForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('show:create')
        self.helper.add_input(Submit('submit', 'Add'))

    def save(self, *args, **kwargs):
        return Show.objects.create_from_rss_url(self.cleaned_data['rss_url'])

class SegmentForm(forms.ModelForm):

    class Meta:
        model = Segment
        fields = ('start_time', 'end_time')

    def __init__(self, *args, **kwargs):
        super(SegmentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('segment:create')
        self.helper.add_input(Submit('submit', 'Create'))

episodes/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, CreateView, DetailView

from rest_framework import generics, viewsets
from rest_framework.renderers import JSONRenderer

from .forms import ShowForm, SegmentForm
from .models import Show, Episode, Segment
from .serializers import EpisodeSerializer

class FeedView(TemplateView):
    template_name = 'episodes/index.html'

    def get_context_data(self, **kwargs):
        context_data = super(FeedView, self).get_context_data(**kwargs)
        episodes = Episode.objects.all().order_by('-released')[:10]
        serializer = EpisodeSerializer(episodes, many = True)
        jsoned = JSONRenderer().render(serializer.data)
        context_data['episodes'] = jsoned
        return context_data

class EpisodeViewSet(viewsets.ModelViewSet):
    serializer_class = EpisodeSerializer
    queryset = Episode.objects.all().order_by('-released')

class ShowListView(ListView):
    model = Show

class ShowCreateView(CreateView):
    model = Show
    form_class = ShowForm

class ShowDetailView(DetailView):
    model = Show

    def get_context_data(self, **kwargs):
        context_data = super(ShowDetailView, self).get_context_data(**kwargs)
        show = context_data['show']
        context_data['episode_list'] = show.episode_set.all().order_by('-released')
        return context_data

def refresh(request, slug):
    """ Create new Episodes for any RSS entries not already in the show """
    if request.method == 'POST':
        show = get_object_or_404(Show, slug = slug)
        show.refresh()
        return redirect('show:detail', slug = slug)

class EpisodeDetailView(DetailView):
    model = Episode

    def get_context_data(self, **kwargs):
        context_data = super(EpisodeDetailView, self).get_context_data(**kwargs)
        episode = context_data['episode']
        context_data['show'] = episode.show
        context_data['segments'] = episode.segments.all()
        context_data['segment_form'] = SegmentForm()
        return context_data

class SegmentDetailView(DetailView):
    model = Segment

class SegmentCreateView(CreateView):
    model = Segment
    form_class = SegmentForm

episodes/templates/episodes/base.html
{% extends 'base.html' %}{% load static %}{% block head %}  <!-- Bootstrap -->  <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->  <!--[if lt IE 9]>    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>  <![endif]-->{% endblock head %}{% block body %}  <div class="container">    {% block header %}    {% endblock %}    <ul class="nav nav-pills">      {% block nav %}      {% endblock %}    </ul>    {% block main %}    {% endblock %}  </div>  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->  <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>  <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>{% endblock body %}

episodes/templates/episodes/episode_detail.html
{% extends 'episodes/base.html' %}
{% load crispy_forms_tags %}

{% block header %}
  <h1>
    <a href="{% url 'show:list' %}"><span class="glyphicon glyphicon-fast-backward"></span></a>
    <a href="{% url 'show:detail' slug=show.slug %}">{{ show.name }}</a></h1>
  <h2>{{ episode.title }}</h2>
{% endblock header %}

{% block nav %}
  {% crispy segment_form segment_form.helper %}
{% endblock nav %}

{% block main %}
  <ul id="id_segment_list" class="list-group">
    {% for segment in segments %}
      <li class="list-group-item">
        {{ segment.start_time}}:{{ segment.end_time }} {{ segment.tags }}
      </li>
    {% empty %}
      <li class="list-group-item">
        (no segments in episode)
      </li>
    {% endfor %}
  </ul>
{% endblock main %}

episodes/templates/episodes/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Soundscapes</title>
    <link href="{% static 'episodes/css/soundscapes.css' %}" rel="stylesheet">
  </head>
  <body>
    <svg>
    </svg>
    <script src="{% static 'd3/d3.js' %}"></script>
    <script src="{% static 'colorbrewer/colorbrewer.js' %}"></script>
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'underscore/underscore.js' %}"></script>
    <script src="{% static 'backbone/backbone.js' %}"></script>
    <script src="{% static 'soundmanager2/script/soundmanager2.js' %}"></script>

    <script src="{% static 'episodes/js/models.js' %}"></script>
    <script src="{% static 'episodes/js/waveform.js' %}"></script>
    <script>
var episodeCollection = new EpisodeCollection;
episodeCollection.reset({{ episodes|safe }});

var waveformView = new WaveformView({collection: episodeCollection});
waveformView.render();

soundManager.setup({
  url: "{% static 'soundmanager2/swf' %}",
  flashVersion: 9,
  preferFlash: false,
  onready: function () {
    //bar.trigger("soundmanager:ready");
  },
  debugMode: false
});
    </script>
  </body>
</html>

episodes/templates/episodes/show_detail.html
{% extends 'episodes/base.html' %}

{% block header %}
  <h1><a href="{% url 'show:list' %}"><span class="glyphicon glyphicon-step-backward"></span></a> {{ show.name }}</h1>
{% endblock header %}

{% block nav %}
  <form action="{% url 'show:refresh' slug=show.slug %}" method="POST" class="navbar-form">
    {% csrf_token %}
    <button type="submit" class="btn btn-default">
      <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
       Refresh</button>
  </form>
{% endblock nav %}

{% block main %}
  <ul id="id_episode_list" class="list-group">
    {% for episode in episode_list %}
      <li class="list-group-item">
        <a href="{{ episode.get_absolute_url }}">{{ episode.title }}</a>
      </li>
    {% empty %}
      <li class="list-group-item">
        (no episodes in feed)
      </li>
    {% endfor %}
  </ul>
{% endblock main %}

episodes/templates/episodes/show_form.html
{% extends 'episodes/base.html' %}
{% load crispy_forms_tags %}

{% block header %}
  <h1><a href="{% url 'show:list' %}"><span class="glyphicon glyphicon-step-backward"></span></a> New Show</h1>
{% endblock header %}

{% block main %}
  {% crispy form form.helper %}
{% endblock main %}

episodes/templates/episodes/show_list.html
{% extends 'episodes/base.html' %}

{% block header %}
  <h1>Shows</h1>
{% endblock header %}

{% block nav %}
    <li role="presentation">
      <a class="btn btn-default" href="{% url 'show:create' %}" role="button">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
         Add Show
      </a>
    </li>
{% endblock nav %}

{% block main %}
  <ul id="id_show_list" class="list-group">
    {% for show in show_list %}
      <li class="list-group-item">
        <a id="id_show_name" href="{{ show.get_absolute_url }}">{{ show.name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock main %}